### PR TITLE
fixes many small performance issues

### PR DESCRIPTION
**Pull request by kypvalanx**
These are all found by Intellij static analysis tools.  i stuck with simple ones that could be found and replaced easily.

### CODE REVIEW

**Comment by grimreaper** [comment]
Hey, this is great - but the tests don't quite pass right now. Mind splitting this up into several different PRs? It might be easier to review.
Also some other thoughts
 - consider splitting up PRs more than about 10 files per file.
- consider skipping code in `gui` and `gui2` directories: they are undergoing modification now and likely will be rewritten.

**Comment by thpr** [comment]
Second that this is great - if you could also look at items that converted from tab indentation to space indentation that would also reduce the impact of some of the changes.

**Comment by LegacyKing** [comment]
Here's the error being generated to also aid you:

`> Task :compileJava
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/EquipmentChoice.java:110: error: illegal start of expression
					for (int j = minValue; j <= maxValue; {
					                                      ^
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/EquipmentChoice.java:111: error: ';' expected
						j += incValue
						             ^
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/EquipmentChoice.java:112: error: illegal start of expression
					})
					 ^
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/EquipmentChoice.java:664: error: illegal start of expression
			for (int j = minValue; j <= maxValue; {
			                                      ^
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/EquipmentChoice.java:665: error: ';' expected
				j += incValue
				             ^
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/EquipmentChoice.java:666: error: illegal start of expression
			})
			 ^
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/Equipment.java:3190: error: illegal start of expression
		for (; eqParent != null; {
		                         ^
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/Equipment.java:3191: error: ';' expected
            eqParent = eqParent.d_parent
                                        ^
/home/travis/build/PCGen/pcgen/code/src/java/pcgen/core/Equipment.java:3192: error: illegal start of expression
        })
         ^
9 errors
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.`

**Comment by kypvalanx** [comment]
np, i'm on it

**Comment by kypvalanx** [comment]
I have reverted all but the addAll calls after instantiation of a collection and one case where an object was being created just to get the class from it.  I also switched all of the spaces to tabs in my changes.

**Comment by kypvalanx** [comment]
I've also removed changes to gui2 files

**Comment by grimreaper** [comment]
tests pass, its one commit, and it looks good: merging.

**Comment by LegacyKing** [comment]
@kypvalanx welcome to the team --> Please join us over on Discord and then I'll send the slack invite after we do a quick onboard.

Discord:  https://discord.gg/A6hWjzw

**Pull request merged**
