### PR TITLE
DATA-2504: [PFAPG] Inquisitor abilities don't add SLAs where relevant

### PR DESCRIPTION
**Pull request by ElroTheOnk**
Added SLAs to Inquisitor abilities

### CODE REVIEW

**Comment by LegacyKing** [comment]
Branch "Master" is not operating at the moment. We're working out a snafu. For the time being, please submit the PR to the "Develop" Branch. As soon as a decision is made regarding the master, Develop will either be merged into the proper branch, or become the main development branch.

**Comment by ElroTheOnk** [comment]
Hi Andrew. My git-fu is exceptionally weak - I've just tried running a PR from github from my branch (which is based off an up-to-date PCGen:master) into PCGen:Develop and it picked up quite a few commits (20 odd) which have nothing to do with my change. How do I isolate my PR to Develop to only the changes I intended?

**Comment by BahamutDragon** [comment]
I saw that. I'll handle it. We're trying to avoid bring in the distorted history introduced by #402

**Comment by BahamutDragon** [comment]
I saw that. Talking with Andrew now. Git can be a fickle beast. Have you tried cherrypicking using sourcetree?

**Comment by LegacyKing** [comment]
Hey Paul. Juggling a few issues at the same time - you're not the only one affected by this issue.

Git will try to correct the missing objects. You'll have to use the cherrypick feature in sourcetree or if that is a bit too difficult, either myself or BD will look at it.

**Comment by BahamutDragon** [comment]
Mates, it is single file with only two lines altered. Grab the file at that commit. Branch from the develop branch. add/commit the change.

**Comment by BahamutDragon** [comment]
Here are the two lines isolated
`Detect Alignment								KEY:Inquisitor ~ Detect Alignment			CATEGORY:Special Ability	TYPE:InquisitorClassFeatures.SpecialQuality.SpellLike																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														DESC:At will, an inquisitor can use detect chaos, detect evil, detect good, or detect law. She can only use one of these at any given time.																																																																																																																																																																																																																																																																																																																																																																																																																																																																				SOURCEPAGE:p.40														SPELLS:Inquisitor|TIMES=ATWILL|CASTERLEVEL=InquisitorLVL|Detect Chaos,11+WIS|Detect Evil,11+WIS|Detect Good,11+WIS|Detect Law,11+WIS`

`Discern Lies								KEY:Inquisitor ~ Discern Lies				CATEGORY:Special Ability	TYPE:InquisitorClassFeatures.SpecialQuality.SpellLike																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														DESC:An inquisitor can discern lies, as per the spell, for %1 rounds per day. These rounds do not need to be consecutive. Activating this ability is an immediate action.|InquisitorLVL																																																																																																																																																																																																																																																																																																																																																																																																																																																													SOURCEPAGE:p.41														SPELLS:Inquisitor|TIMES=InquisitorLVL|TIMEUNIT=rounds/day|CASTERLEVEL=InquisitorLVL|Discern Lies,14+WIS`

I am happy to help, since Andrew is helping me with an issue with a CHOOSER problem.

**Comment by ElroTheOnk** [comment]
Thanks for the help - think I've understood and complied. Assuming the new PR checks out ok, I'll kill this one in due course...

**Comment by ElroTheOnk** [comment]
I know the change was trivial, but things like this are an excuse to learn how to use these new-fangled tools so have tried to do it "properly" ;-)

**Pull request closed without merging**
