### PR TITLE
Fix bug: DATA-2629 ACG - Arcanist / School Savant archetype

### PR DESCRIPTION
**Pull request by romen**
Citing from ACG p.78 School Savant (Archetype):

"*School Focus(Su): At 1st level, a school savant chooses a school of magic. The arcanist gains the abilities granted by that school, as the arcane school class feature of the wizard, treating her arcanist level as her wizard level for these abilities.. She can also further specialise by selecting one of the subschools found in the APG. __In addition the arcanist can prepare one additional spell per day of each level she can cast, but this spell must be chosen from the selected school__.*"

Commits 7e6c64f033380199171af168c147dd02a9541a20 and d0f6f44f20b66e9eafc198f17951a8fbcf5d3233 already addressed this, with the caveat that the extra prepared slot cannot be restricted to the specific school and it's up to the user to ensure this.

But commit 2e88c601fb3a4e5c6e1ae176d6c91e110627b807 introduced a regression on the previous fix: in rewriting each school/subschool description, the SPELLCAST bonus has been switched to the SPELLKNOWN bonus.

This does not take in accounte that the current workaround in place for Arcanist states:

```
# COMMENT: Arcanists have sorcerer/wizard spells as a spell list, a spell book of known spells, a chosen list of castable spells per day, and a number of spell slots per day.
# WORKAROUND: "CAST" is used for spells prepared; ArcanistCastLVL_n used for number of spells castable per day of each level
```

This commit simply reverts BONUS:SPELLKNOWN to BONUS:SPELLCAST.

### CODE REVIEW

**Comment by romen** [comment]
Link to the issue on JIRA: https://pcgenorg.atlassian.net/browse/DATA-2629

**Comment by romen** [comment]
I also have a patch ready to add an extra prepared slot for lvl0 spells, but I'm going to wait on your feedback before adding it to the pull request.

**Comment by romen** [comment]
What about the lvl0 extra prepared slot? Should I open a new pull request?

**Comment by LegacyKing** [comment]
new issues, new PR please.


Thanks,

**Comment by romen** [comment]
Opened: #1785 

Thanks!

**Pull request merged**
