### PR TITLE
update gradle to latest 2.x series

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by cpmeister** [comment]
why are you deleting pcgen.sh?

**Comment by grimreaper** [comment]
uuuuh, I thought I was recreating it. One sec

**Comment by cpmeister** [comment]
wait, nvm I think it should be deleted

**Comment by Zaister** [comment]
pcgen.sh is being deleted? why?

**Comment by LegacyKing** [comment]
Seconded. pcgen.sh is used by our Linux users to start the program. It
should be built as part of the compile/build process.

**Pull request merged**
