### PR TITLE
PFS season 9-01 to 21

### PR DESCRIPTION
**Pull request by mjmeans**

### CODE REVIEW

**Comment by LegacyKing** [comment]
Mark - https://github.com/PCGen/pcgen/pull/4106 and https://github.com/PCGen/pcgen/pull/4113 and https://github.com/PCGen/pcgen/pull/4113 ALL contain the exact same commits! Please clean these branches up.

**Comment by LegacyKing** [comment]
Mark - https://github.com/PCGen/pcgen/pull/4106 and https://github.com/PCGen/pcgen/pull/4113 and https://github.com/PCGen/pcgen/pull/4113 ALL contain the exact same commits! Please clean these branches up.

**Comment by LegacyKing** [comment]
Still Conflicted.

**Comment by LegacyKing** [comment]
@mjmeans the only method to fix is to PULL w/ rebase of Master, then Push w/ Lease this back up.

**Comment by mjmeans** [comment]
So I backed up my branch to a separate location. I used "git rebase --force upstream/master" to start the process. The expected behavior is that all commits that were already merged into upstream/master will now be invalid because the current state will already have included those changes. So those commits will not be able to be merged a second time. So I "git rebase --skip" each of those commits that were not able to be merged until the rebase finished. Then I copied the backup of my branch over top of the existing local repo to confirm that all files were in their correct new state. They were, so no new commits were needed. Then I used "git push -f". Hopefully this will do it.

**Comment by mjmeans** [comment]
It looks good and my test char for all available season 9 chronicle boons, abilities and items still loads without errors.

**Pull request merged**
