### PR TITLE
WIP: Update Deps and build tools

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by LegacyKing** [comment]
* What went wrong:
Execution failed for task ':pmdMain'.
> java.lang.IllegalArgumentException: Unable to exclude rules [GuardLogStatement]; perhaps the rule name is mispelled?

**Comment by karianna** [comment]
Yeah I can replicate that locally, a bunch of the PMD config needs to change to meet the latest version, I'll tinker away over the next weeks

**Comment by mertonmonk** [comment]
Should I merge this? I assume that the commit means it's ready, but want to confirm.

**Comment by LegacyKing** [comment]
No @mertonmonk - If Travis is failing, we need to address the issue before we merge. Codacy and AppVeyor are not critical, but Travis is running all the PCGen code and data tests.

**Comment by karianna** [comment]
I need to fix the PMD configuration (it's a major upgrade)

**Comment by karianna** [comment]
Finally got this fixed :-)

**Comment by karianna** [comment]
@thpr - it sounds like the pmd check should have 0 issues and therefore we should fail the build?

In that case I probably need to pair with you and go through the 5K warnings (probably new categories introduces by PMD 6.0).  Let me know if that suits!

**Comment by karianna** [comment]
@grimreaper I've ping you an email if you'd like to pair on this (I hear you're the PMD expert!)

**Comment by grimreaper** [comment]
Lets split this into 3 commits:
- PMD changes
- build tool changes
- other dep changes

This makes it easier to bisect/revert if we need to.

**Comment by karianna** [comment]
@grimreaper OK, I'll close this and send in 3 separate PR's

**Pull request closed without merging**
