### PR TITLE
Fix bug: DATA-3076 Evangelist align class is broken

### PR DESCRIPTION
**Pull request by LegacyKing**

### CODE REVIEW

**Comment by LegacyKing** [comment]
@grimreaper  @cpmeister  I'm baffled and astounded by Travis... The error makes absolutely no sense. None of the mentioned systems TOUCH Inner Sea Gods. Not even PFS at the time I am writing this.

It's like the system is going out of it's way to make noise.

**Comment by LegacyKing** [comment]
Can anyone explain why PCGen is loading Inner Sea Gods when I load just the Core Supplement loader?

PCC:@/pathfinder/paizo/roleplaying_game/core_rulebook/core_rulebook.pcc
PCC:@/pathfinder/paizo/roleplaying_game/bestiary/bestiary.pcc
PCC:@/pathfinder/paizo/roleplaying_game/bestiary_2/bestiary_2.pcc
PCC:@/pathfinder/paizo/roleplaying_game/bestiary_3/bestiary_3.pcc
PCC:@/pathfinder/paizo/roleplaying_game/advanced_players_guide/advanced_players_guide.pcc
PCC:@/pathfinder/paizo/roleplaying_game/advanced_race_guide/advanced_race_guide.pcc
PCC:@/pathfinder/paizo/roleplaying_game/ultimate_combat/_ultimate_combat.pcc
PCC:@/pathfinder/paizo/roleplaying_game/ultimate_magic/_ultimate_magic.pcc
PCC:@/pathfinder/paizo/roleplaying_game/ultimate_equipment/ultimate_equipment.pcc
# Using new file style
PCC:@/pathfinder/paizo/roleplaying_game/ultimate_campaign/_ultimate_campaign.pcc
PCC:@/pathfinder/paizo/roleplaying_game/advanced_class_guide/_advanced_class_guide.pcc

**Comment by LegacyKing** [comment]
This works, but I will not merge until the baffling mystery is dealt with...

**Comment by Zaister** [comment]
Bestiary 3 pulls in isg_deities.lst, but only Ahriman.

**Comment by LegacyKing** [comment]
@Zaister Yeah, odd how it's pulling in all abilities when it shouldn't. I figured it out. Now to correct a proficiency issue in Side Winder

**Pull request merged**
