### PR TITLE
ItemFacet: return an Optional from `get`

### PR DESCRIPTION
**Pull request by grimreaper**
This makes it clear whether or not we're handling `null` properly. There 
are several cases here that look like bugs. I've attempted to change
nothing about the semantics. If you find bugs of the sort "we should add a
check there", but there wasn't one before, please comment, but I'll fix
them in a followup.

In a couple of cases we have some odd APIs (e.g., `.get().get()`) but IMHO
the tradeoffs are worth it.

### CODE REVIEW

**Comment by thpr** [comment]
I would like this to stay pending for a bit to evaluate whether this impacts merging with a significant number of local branches

**Comment by grimreaper** [comment]
> Also, this code unconditionally calls .get() meaning the optional is rather useless. So this leads a developer to think they are optional, which is a problem given actual behavior.
The point is that this makes it clear when this happens. Every unconditional `.get` is a place where a bug likely exists.

**Comment by thpr** [comment]
But again, that's confusing.  If you are concerned about nulls, do requireNotNull, not turning the underlying into Optional when they aren't truly optional.  The semantics this has are deceptive.

**Comment by grimreaper** [comment]
> But again, that's confusing. If you are concerned about nulls, do requireNotNull, not turning the underlying into Optional when they aren't truly optional. The semantics this has are deceptive.

It is my understanding that this is actually optional in many cases, but only required in a few. Is that not the case?

**Comment by grimreaper** [comment]
We're eliminating Facet anyways, so closing this. Once we have a newer system I'll take a closer look at what should `Optional` vs not.

**Pull request closed without merging**
