### PR TITLE
NEWSOURCE-200 PFS

### PR DESCRIPTION
**Pull request by mjmeans**

### CODE REVIEW

**Comment by LegacyKing** [comment]
Fails tests.

**Comment by LegacyKing** [comment]
Can't find "/pcgen/data/pathfinder/paizo/roleplaying_game/advanced_class_guide/advanced_class_guide.pcc"

**Comment by LegacyKing** [comment]
Should be "/pcgen/data/pathfinder/paizo/roleplaying_game/advanced_class_guide/_advanced_class_guide.pcc"

**Comment by mjmeans** [comment]
I changed the file name reference to have a leading _. I don't understand why it still failed tests. Error reading a file I didn't change, on an ability I didn't .MOD?

**Comment by LegacyKing** [comment]
Interesting, the error isn't yours. It's from another commit that shouldn't be in the repo...

**Comment by LegacyKing** [comment]
I'll merge and patch that quickly

**Pull request merged**
