### PR TITLE
Fix various installer issues.

### PR DESCRIPTION
**Pull request by javydreamercsw**
The issue for the missing exe file was due to it being generated prior to it being created. This changes make sure it is generated before the copy is attempted.

### CODE REVIEW

**Comment by javydreamercsw** [comment]
The build failure seems to be related tho this issue: https://sourceforge.net/p/launch4j/feature-requests/74/

Not related with the code itself.

**Comment by LegacyKing** [comment]
Are we able to resolve this, or do we need to revert the work till the problem is resolved?

**Comment by javydreamercsw** [comment]
The problem is on the server running the build. Not sure how much you guys have control over that.

This is due to the build now generating the exe file each time vs. having it as part of the controlled files. I guess another option would be to just have the exe there, but I would need to remove and change lots of stuff from what I did.

**Comment by LegacyKing** [comment]
https://github.com/travis-ci/travis-ci/issues/5176

This is what you need to add to your .travis.yml to install the missing 32-bit libs:

sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install lib32z1 lib32ncurses5

**Comment by LegacyKing** [comment]
I'm testing it on my end, and doing a build test right now. So far so good.

**Comment by javydreamercsw** [comment]
Got a green by Travis :D

**Comment by javydreamercsw** [comment]
Pending your test and it should be ready. Thanks for the help!

**Comment by LegacyKing** [comment]
I got a message:
  File: "C:\Projects\pcgen\pcgen\build/nsis/jre/jre_64/*.*" -> no files found. (C:\Projects\pcgen\pcgen/installers/win-installer/pcgen.nsis:167)
  File: "C:\Projects\pcgen\pcgen\build/nsis/jre/jre_32/*.*" -> no files found. (C:\Projects\pcgen\pcgen/installers/win-installer/pcgen.nsis:169)

Beyond that, the installer is working. The versioning looks cleaner. Only test left is if the exe shortcut works! After that, I'll be happy to merge in this "Hot fix" in... since I consider this an extension of work that was already approved by Connor.

**Comment by javydreamercsw** [comment]
Hmmm. Those are the files used for embedding the jre. I'll check that file in a bit.

**Comment by LegacyKing** [comment]
Okay, main issue still remains. I do not have any exe file being created.

**Comment by LegacyKing** [comment]
I'm left with the install folder having no pcgen.exe file, and an empty jre folder as well.

**Comment by javydreamercsw** [comment]
Checking...

**Comment by javydreamercsw** [comment]
How do you call the installer build? Want to know what are you running to troubleshoot.

**Comment by javydreamercsw** [comment]
I'm cloning the repository as I didn't have it at home.

**Comment by javydreamercsw** [comment]
Are you running all task?

**Comment by javydreamercsw** [comment]
I think I found the issue, if it was called from all->build task. Testing it now. I see it downloading the JRE and all so it seems to be working. Won't commit until I check the installer output.

**Comment by LegacyKing** [comment]
Sent email - join me in hipchat to discuss.

**Comment by LegacyKing** [comment]
And the tasks for testing the build are:
fullZip
buildNsis

**Comment by LegacyKing** [comment]
My test branch is up to date with your master, and even just doing the buildNsis only, my shortcut can't find the pcgen.exe file.

**Comment by javydreamercsw** [comment]
Try running create Executive alone

**Comment by LegacyKing** [comment]
As long as task fullZip + buildNsis is used together, this works. Task buildNsis will not work on its own, as it failed to execute createExe. I can update the release notes to note this limitation.

**Pull request merged**
