### PR TITLE
NEWTAG-597 Add Dice Format

### PR DESCRIPTION
**Pull request by thpr**

### CODE REVIEW

**Comment by thpr** [comment]
This is approved even with Codacy complaints since they are all in utest code.

**Comment by LegacyKing** [comment]
It's been a month, can we merge this?

**Comment by LegacyKing** [comment]
@grimreaper can check this out... but I'm merging this and the CDOM fix... hoping that will correct the GETFACT error we are having. If not, will need to investigate.

**Comment by LegacyKing** [comment]
Apparently it won't build... reverting.

**Pull request merged**
