### PR TITLE
Standardized Equipmod keys

### PR DESCRIPTION
**Pull request by Llisandur**
aa_ -> changed keys
acg_ -> changed keys, fixed choose on blood-hunting and spirit-hunting
aco_ -> changed keys
anar_ -> changed keys, added sourcepage
ap10_ -> changed keys
ap14_ -> changed keys, standardized noqual entries (ap14, ap61, tg, pfscs_pzogwk0001), added armor save bonus to abilities
ap61_ -> changed keys, standardized noqual entries (ap14, ap61, tg, pfscs_pzogwk0001), fix type prerequisites
apg_ -> changed keys, combined corrosive burst to a single a equipmod
arg_ -> changed keys, fix some eqmod setting masterwork for no reason, fix type prerequisites, reactivate and fix deadly weapon special ability
b3_ -> changed keys
bos_ -> changed keys, made some names clearer
cfd_ -> changed key
cop_ -> added keys
cr_ -> changed keys, changed magic item bonus type and prerequisite to slot rather than first type listed, fixed staff spell pricing
dh_ -> changed keys
dtt_ -> changed keys
eog_ -> changed keys
ghh_ -> changed keys
ism_ -> changed keys, changed tattoos to only use base slot name
iswg_ -> changed keys
ssg/_kkass_ -> changed keys
ma_ -> changed keys
mm_ -> changed keys
mtt_ -> changed keys, fixed sourcepage
pcfg_ -> changed keys
pfs_arg_ -> changed keys
pfs_b3_ -> changed keys
pfs_bos_ -> changed keys
pfs_iswg_ -> changed keys
pfs_ue_ -> changed keys
pfscs_PZOGWK0001_ -> standardized noqual entries (ap14, ap61, tg, pfscs_pzogwk0001)
pfscs_S5_ -> changed keys
pfsfg_ -> changed keys
pfsp_ -> changed keys
ag/pos_ -> added keys
psand_ -> changed keys
dsp/psionics_expanded_ -> changed keys
dsp/psionics_unleashed_ -> changed keys, changed magic item bonus type and prerequisite to slot rather than first type listed
qac_ -> added keys
qgtte_ -> changed keys
rotr_ -> changed keys, added sourcepage
ap/rr_ -> changed keys
rtt_ -> changed keys, fixed spear sling type from crossbow to spearsling
sgg/sggah_ -> changed keys
sos_ -> changed keys
teog_ -> added keys
tg_ -> changed keys, standardized noqual entries (ap14, ap61, tg, pfscs_pzogwk0001), changed technological gear type to technological to match with magic and enhancement types
uc_ -> changed keys, fixed primitive materials to the same as ultimate equipment, differentiated deadly weapon special property and deadly weapon special ability
ue_ -> changed keys, differentiated deadly weapon special property and deadly weapon special ability, removed shattering from earthenflail (second printing removed it)
dsp/up_ -> changed keys
wmh_ -> added keys

### CODE REVIEW

**Comment by LegacyKing** [comment]
Fix the three bugs introduced -> 

pcgen.persistence.lst.DataLoadTest > testLoadSources[Pathfinder Society Organized Play Mode] FAILED
    org.junit.ComparisonFailure: Errors encountered while loading Pathfinder Society Organized Play Mode expected:<[]> but was:<[Unconstructed Reference: EquipmentModifier MATERIAL_BRONZE,
    Unconstructed Reference: EquipmentModifier SPROP_FRAGILE,
    Unconstructed Reference: EquipmentModifier WEAPON_SA_ALLYING]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at pcgen.persistence.lst.DataLoadTest.testLoadSources(DataLoadTest.java:160)

**Comment by LegacyKing** [comment]
Okay, I'm looking at this, and I'm trying to avoid confusing nomenclature, which this looks to retain.

There is no reason to continue using underscored connections. Is there any reason why we can't use simpler KEY naming conventions?

**Comment by Llisandur** [comment]
The reason I kept the all-caps was for visibility, and I kept the underscores so that the entire key can be selected at once. It also cuts down on space-based errors. You can't use just the names for the keys because I ran into at least three sets of abilities that overlap names.

**Comment by Llisandur** [comment]
What lst file is causing the errors?

**Comment by LegacyKing** [comment]
No idea on the file. And why isn't the Core version good enough?

> Adamantine		KEY:Adamantine (Ammo)		
> Adamantine		KEY:Adamantine (Light Armor)	
> Adamantine		KEY:Adamantine (Medium Armor)	
> Adamantine		KEY:Adamantine (Heavy Armor)	
> Adamantine		KEY:Adamantine (Weapon)		
> Mithral		KEY:Mithral (Light Armor)	
> Mithral		KEY:Mithral (Medium Armor)	
> Mithral		KEY:Mithral (Heavy Armor)	
> Mithral		KEY:Mithral (Shield)		
> Mithral		KEY:Mithral (Item)		
> Darkwood		KEY:Darkwood			
> Dragonhide		KEY:Dragonhide			
> Cold Iron		KEY:Cold Iron			
> Alchemical Silver	KEY:Alchemical Silver		
>

**Comment by Llisandur** [comment]
Try searching "Bane". It comes up with all kinds of things that aren't EQMOD KEYs. Also, currently the "Deadly" weapon property is broken, and wouldn't be fixed using that style. There's the magic weapon ability called "Deadly" that does one thing and also a "Deadly" weapon quality that does something else.

I tried to make sure that everything can be uniquely identified initially for as many keys as possible, rather adding exceptions later. Also, at a glance, you can tell if a particular key is a magic ability, a mundane modification, a material, etc.

**Comment by karianna** [comment]
@LegacyKing Are you able to take a new look and see if you're happy?

**Pull request merged**
