### PR TITLE
Preliminary Support for GH Actions

### PR DESCRIPTION
**Pull request by K-orne**
As requested on Discord.

Do note that the build does not include the new(?) build steps ie deploy a full distributable with the new changes to the build process

### CODE REVIEW

**Comment by karianna** [comment]
Can you try to get this to Java 16?  You'll need that now :-)

**Comment by TheSpiritof69** [comment]
> Can you try to get this to Java 16? You'll need that now :-)

Hi @karianna, it does build now against AdoptJDK 16, though it does not create the redistributable including the JDK, I think.
Admittedly I'm not really up to speed with Java/Gradle.

Have at it :)

**Comment by grimreaper** [comment]
I approved this run to see if it completes. If it looks good I think we can merge.

**Comment by LegacyKing** [comment]
@karianna and @grimreaper where are we on this one?

**Comment by TheSpiritof69** [comment]
@LegacyKing as far as I can see it, the problem with nsis remains the same, I'm not sure if its possible to integrate that into the java build container.

So far it seems the build step is somehow picked up implicitly from an existing NSIS installation on the build host? Was that something that was done in jenkins before? Is it possible to separate that step out?

**Comment by LegacyKing** [comment]
BuildNSIS is something installed on the windows machine of the host, so I'm not sure how we proceed, since that's part of the distribution package.

**Comment by karianna** [comment]
We are getting closer:  There's a series of IT test failures (may have been around for a long time.

pcGenGUIElwoodTest > testElwood() FAILED
    org.opentest4j.AssertionFailedError: Expected child nodelist length '1' but was '0' - comparing <total...> at /character[1]/weapons[1]/unarmed[1]/total[1] to <total...> at /character[1]/weapons[1]/unarmed[1]/total[1] ==> expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
        at app//pcgen.inttest.PcgenFtlTestCase.runTest(PcgenFtlTestCase.java:117)
        at app//pcgen.inttest.game_modern.pcGenGUIElwoodTest.testElwood(pcGenGUIElwoodTest.java:36)

pcGenGUIIlyanaTest > testIlyana() FAILED
    org.opentest4j.AssertionFailedError: Expected child nodelist length '1' but was '0' - comparing <total...> at /character[1]/weapons[1]/unarmed[1]/total[1] to <total...> at /character[1]/weapons[1]/unarmed[1]/total[1] ==> expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
        at app//pcgen.inttest.PcgenFtlTestCase.runTest(PcgenFtlTestCase.java:117)
        at app//pcgen.inttest.game_modern.pcGenGUIIlyanaTest.testIlyana(pcGenGUIIlyanaTest.java:35)

pcGenGUIPfrpgClericTest > testCode() FAILED
    org.opentest4j.AssertionFailedError: Expected child nodelist length '109' but was '105' - comparing <ability_objects...> at /character[1]/ability_objects[1] to <ability_objects...> at /character[1]/ability_objects[1] ==> expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
        at app//pcgen.inttest.PcgenFtlTestCase.runTest(PcgenFtlTestCase.java:117)
        at app//pcgen.inttest.game_pathfinder.pcGenGUIPfrpgClericTest.testCode(pcGenGUIPfrpgClericTest.java:19)

pcGenGUIPfrpgGoldielocksTest > testCode() FAILED
    org.opentest4j.AssertionFailedError: Expected child nodelist length '127' but was '125' - comparing <ability_objects...> at /character[1]/ability_objects[1] to <ability_objects...> at /character[1]/ability_objects[1] ==> expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
        at app//pcgen.inttest.PcgenFtlTestCase.runTest(PcgenFtlTestCase.java:117)
        at app//pcgen.inttest.game_pathfinder.pcGenGUIPfrpgGoldielocksTest.testCode(pcGenGUIPfrpgGoldielocksTest.java:20)

pcGenGUIPfrpgPaladinTest > testCode() FAILED
    org.opentest4j.AssertionFailedError: Expected child nodelist length '115' but was '111' - comparing <ability_objects...> at /character[1]/ability_objects[1] to <ability_objects...> at /character[1]/ability_objects[1] ==> expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
        at app//pcgen.inttest.PcgenFtlTestCase.runTest(PcgenFtlTestCase.java:117)
        at app//pcgen.inttest.game_pathfinder.pcGenGUIPfrpgPaladinTest.testCode(pcGenGUIPfrpgPaladinTest.java:33)

pcGenGUIPfrpgRogueTest > testCode() FAILED
    org.opentest4j.AssertionFailedError: Expected text value '+8' but was '+9' - comparing <total ...>+8</total> at /character[1]/saving_throws[1]/saving_throw[1]/total[1]/text()[1] to <total ...>+9</total> at /character[1]/saving_throws[1]/saving_throw[1]/total[1]/text()[1] ==> expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
        at app//pcgen.inttest.PcgenFtlTestCase.runTest(PcgenFtlTestCase.java:117)
        at app//pcgen.inttest.game_pathfinder.pcGenGUIPfrpgRogueTest.testCode(pcGenGUIPfrpgRogueTest.java:33)

pcGenGUISFmechanicTest > testCode() FAILED
    org.opentest4j.AssertionFailedError: Expected text value 'Athletics +24, Computers +34, Engineering +33, Medicine +29, Perception +29, Physical Science +28, Piloting +28, Profession (Maintenance Worker) +27, Sense Motive +6, Stealth +7, Survival +6' but was 'Athletics +24, Computers +34, Engineering +36, Medicine +29, Perception +27, Physical Science +28, Piloting +28, Profession (Maintenance Worker) +27, Stealth +7, Survival +6' - comparing <list_mods ...>Athletics +24, Computers +34, Engineering +33, Medicine +29, Perception +29, Physical Science +28, Piloting +28, Profession (Maintenance Worker) +27, Sense Motive +6, Stealth +7, Survival +6</list_mods> at /character[1]/skills[1]/list_mods[1]/text()[1] to <list_mods ...>Athletics +24, Computers +34, Engineering +36, Medicine +29, Perception +27, Physical Science +28, Piloting +28, Profession (Maintenance Worker) +27, Stealth +7, Survival +6</list_mods> at /character[1]/skills[1]/list_mods[1]/text()[1] ==> expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
        at app//pcgen.inttest.PcgenFtlTestCase.runTest(PcgenFtlTestCase.java:117)
        at app//pcgen.inttest.game_starfinder.pcGenGUISFmechanicTest.testCode(pcGenGUISFmechanicTest.java:20)

pcGenGUISFsoldierTest > testCode() FAILED
    org.opentest4j.AssertionFailedError: Expected text value 'Acrobatics +13, Athletics +12, Engineering +15, Medicine +15, Piloting +19' but was 'Acrobatics +18, Athletics +17, Engineering +15, Medicine +15, Piloting +19' - comparing <list_mods ...>Acrobatics +13, Athletics +12, Engineering +15, Medicine +15, Piloting +19</list_mods> at /character[1]/skills[1]/list_mods[1]/text()[1] to <list_mods ...>Acrobatics +18, Athletics +17, Engineering +15, Medicine +15, Piloting +19</list_mods> at /character[1]/skills[1]/list_mods[1]/text()[1] ==> expected: <false> but was: <true>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at app//org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at app//org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
        at app//pcgen.inttest.PcgenFtlTestCase.runTest(PcgenFtlTestCase.java:117)
        at app//pcgen.inttest.game_starfinder.pcGenGUISFsoldierTest.testCode(pcGenGUISFsoldierTest.java:20)

**Comment by karianna** [comment]
@K-orne I think that last commit should have been a rebase.

**Comment by K-orne** [comment]
Realistically this PR has passed the stage of being acceptable a year ago. It should probably be closed.

**Pull request closed without merging**
