### PR TITLE
Inspired_panache_fix

### PR DESCRIPTION
**Pull request by evilpixie87**
Added defines and aspect to Inspired Blade Panache

### CODE REVIEW

**Comment by LegacyKing** [comment]
Why'd we drop the display ability?

**Comment by evilpixie87** [comment]
I was helping someone in HipChat before work and this was just the way I found to make things work after 2 or 3 failures. Was rushing a bit because of the hour. I can replace it if you'd prefer.

**Comment by LegacyKing** [comment]
It looks like it had a purpose? Don't want to remove it, if it did...

**Comment by evilpixie87** [comment]
OK, I put that back!

**Pull request merged**
