### PR TITLE
Courtly_Hunter_fix

### PR DESCRIPTION
**Pull request by evilpixie87**
Fixed a variable name

### CODE REVIEW

**Comment by grimreaper** [comment]
CourtlyHunterAnimalFocusACPool -> CourtlyHunterFocusAnimalACPool

Seems reasonable though I'd go the other direction.

**Comment by evilpixie87** [comment]
Requested changes are in

**Comment by LegacyKing** [comment]
I don't think any push happened, still show original issues.

**Comment by evilpixie87** [comment]
Ok, tried to fix it again....

**Pull request merged**
