### PR TITLE
Fix munted newlines inside code blocks.

### PR DESCRIPTION
**Pull request by LiaungYip**
One of the automated formatting tools I used earlier - probably BeautifulSoup - doesn't know that whitespace inside `<code>` tags is significant.

Undo the munted formatting introduced by that tool.

### CODE REVIEW

**Comment by LegacyKing** [comment]
Gonna be awhile before I can review this.

**Comment by LiaungYip** [comment]
It's an all-auto change; just backs out a previous fubar I committed.

**Comment by LegacyKing** [comment]
I'll trust no hidden gotcha's like entire pages missing then?

**Comment by LiaungYip** [comment]
No, I've scanned over the 92 changed files in my diff tool and nothing blatant jumped out at me.

**Pull request merged**
