### PR TITLE
Restore 8 files from commit 80756ba, which were wiped out in commit a…

### PR DESCRIPTION
**Pull request by LiaungYip**
…32a162.

### CODE REVIEW

**Comment by Nylanfs** [comment]
Hey Lewis, could you change line 1487 of the publishersandsources.html to the following?

<p class="indent2">This website and program uses trademarks and/or copyrights owned by Paizo Inc., which are used under Paizo's Community Use Policy. We are expressly prohibited from charging you to use or access this content. This website and program is not published, endorsed, or specifically approved by Paizo Inc. For more information about Paizo's Community Use Policy, please visit paizo.com/communityuse. For more information about Paizo Inc. and Paizo products, please visit paizo.com.</p>

**Comment by LiaungYip** [comment]
Will do as new commit after this is merged.

**Comment by LegacyKing** [comment]
Thanks for the fast patch.

**Comment by LiaungYip** [comment]
@Nylanfs , #591 .

**Pull request merged**
