### PR TITLE
Remove the download of zlib128-dll.zip #4109

### PR DESCRIPTION
**Pull request by tildar**
I can not find any reason for doing the download.
It does not seem to be used in any way, therefore I suggest we
stop downloading it.

### CODE REVIEW

**Comment by LegacyKing** [comment]
@javydreamercsw these are changes you made. Can you answer what the file is used for?

**Comment by javydreamercsw** [comment]
If I remember correctly this is used by the installer building process.

**Comment by tildar** [comment]
If it's necessary for the building process, why did travis build successful without it in this case?

**Comment by karianna** [comment]
The travis build isn't a full windows deployment build right?

**Comment by tildar** [comment]
@karianna I'm not sure weather or not travis being a "windows deployment build" is even an issues here. 

The issues as I see it is that we currently have TRAVIS configured to dl the zlib file, which seems to me to indicate that it should be needed by the build ON TRAVIS is some way. There are times when this DL fails to work for various reasons, causing the build to fail prematurely. Removing the DL did not cause the build to fail, and removes the failure point that can cause an issue. Thuse I have to question why travis is configured to DL the zlib?

**Comment by javydreamercsw** [comment]
This is because that library is needed for NSIS to work. Travis tries to build the installer as well due to other nightmares in the past when a release was crippled with the installer not working for whatever reason.

**Comment by javydreamercsw** [comment]
I vote against merging this unless the team is willing to not check the installer works on a regular basis which was requested not long ago resulting in part on the changes being removed.

**Comment by tildar** [comment]
I'll defer to javydreamercsw o this then. still seems fishy to me, but not worth the hassle to keep digging.

**Pull request closed without merging**
