### PR TITLE
* [test] Eliminate CompareDeadband matcher

### PR DESCRIPTION
**Pull request by grimreaper**
In an effort to move to more standard tests remove the bool not custom
test matcher.

While here, use assertThat

### CODE REVIEW

**Comment by karianna** [comment]
Codacy issues.

**Comment by karianna** [comment]
@grimreaper Lots of new Codacy issues on this PR

**Comment by grimreaper** [comment]
codacy issues resolved

**Comment by LegacyKing** [comment]
@grimreaper Codacy still showing errors...

**Comment by LegacyKing** [comment]
The issue is LINE LENGTH -- Line is longer than 120 characters (found xxx)

**Pull request merged**
