### PR TITLE
Temporarily disable broken unit tests - Dave, Eve and Fran. Requires …

### PR DESCRIPTION
**Pull request by LegacyKing**
…Code Intervention to handle.

@jdempsey-au temporary patch till we get the unit tests fixed.

### CODE REVIEW

**Comment by jdempsey-au** [comment]
Why would we do this - they would be indicating a character affecting error!

**Comment by LegacyKing** [comment]
Your call. The brokeness is a lack of pcg saving the CATEGORY=Feat state from FEATSELECTION, which consequently changed to ABILITYSELECTION which does require said CATEGORY. All three broken tests share this compatibility flaw.

**Comment by LegacyKing** [comment]
This:
`ABILITY:FEAT|TYPE:NORMAL|CATEGORY:FEAT|KEY:Choose Feat Selection|APPLIEDTO:ChooseSelection_StackNoChoiceFeat,ChooseSelection_StackChoiceFeat(Ride),ChooseSelection_NoStackChoiceFeat(Tumble)|TYPE:Test45`

needs to be like this:
`ABILITY:FEAT|TYPE:NORMAL|CATEGORY:FEAT|KEY:Choose Feat Selection|APPLIEDTO:CATEGORY=FEAT&pipe;ChooseSelection_NoChooseFeat,CATEGORY=FEAT&pipe;ChooseSelection_NoStackChoiceFeat&pipe;Ride|TYPE:Test45`

**Comment by jdempsey-au** [comment]
Then the correct fix in the pcg loader.Is there a bug raised for it?

**Comment by LegacyKing** [comment]
There is now.

**Comment by jdempsey-au** [comment]
Thanks Andrew, I'll have a look into it

**Comment by jdempsey-au** [comment]
These tests have now been fixed. I'll close this PR.

**Pull request closed without merging**
