### PR TITLE
Enable running with junit 5

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by karianna** [comment]
The Travis build didn't seem to really show the tests running?

**Comment by grimreaper** [comment]
hrm. It worked locally. I'll try to figure out what's going on, but this won't happen for a while.

**Comment by grimreaper** [comment]
Perhaps I got the order of events wrong locally. Pushed a change; lets see if this fixes it.

**Comment by karianna** [comment]
Take a look at the Travis output, maybe its suppressing something, I see the task get started/executed?  But I'd have expected to see something like Ran X tests, and I don't see that.

**Comment by thpr** [comment]
I'm concerned if this isn't running tests.  I'd also like to have a chance to bring this down locally and make sure it works in the Eclipse IDE.  It took years for JUnit 4 and Eclipse to play well, which is why we still have some funky tests hanging about.

**Comment by karianna** [comment]
FWIW - when I run `gradlew clean test` it seems to execute them

**Comment by karianna** [comment]
@thpr Will let you review and merge once you're happy.

**Comment by LegacyKing** [comment]
Yeah, the output runs tests and hides them if they pass.  @thpr any chance to give this a test on your local build?

**Comment by LegacyKing** [comment]
And are we up and running with Jenkins? We can give this a good run against the tests with the autobuild as well.

**Comment by grimreaper** [comment]
ping?

**Comment by javydreamercsw** [comment]
I've been seeing that error in Travis recently.

**Pull request merged**
