### PR TITLE
Improve documentation for `SAB` tag.

### PR DESCRIPTION
**Pull request by LiaungYip**

### CODE REVIEW

**Comment by LiaungYip** [comment]
This patch should probably pass the Documentation Team gatekeepers (Barak, Eric C Smith?) See http://wiki.pcgen.org/Documentation .

**Comment by LegacyKing** [comment]
I'm curious as to how long you would like me to wait before I review this then? 

Barak is retired, Eric is on leave.

**Comment by LiaungYip** [comment]
Ha ha. Go on, then...

Li-aung "Lewis" Yip, B.Eng./B.Sc. Hons 1 MIEEE GradIEAust | PO Box 5722,
PERTH St George's Tce, WA 6831, Australia | +61 4 0681 1599 |
liaung.yip@ieee.org | PGP 208F DA83 (http://pgp.webtru.st)

"Tandis qu'ils dorment, nous gagnerons."

**Comment by LegacyKing** [comment]
For whatever reason, github isn't doing any change differential... guess I'll be doing this the hard way.

**Comment by LiaungYip** [comment]
Commit [`Run HTML Tidy.	cdbdca8`](https://github.com/LiaungYip/pcgen/commit/cdbdca86e2142f3473afcd37d505d66f83d22a02) was very noisy - the entire document was reformatted (indenting, etc.) using an automatic tool. Github won't do a diff because there are too many changes.

The actual content changes are in [`Improve documentation for `SAB` tag.	 f2809eb`.](https://github.com/LiaungYip/pcgen/commit/f2809eb225b9b2b5d6e56d0c40b21500b70cc79e). This commit is much smaller, and GitHub will give you the diff just fine.

**Comment by LegacyKing** [comment]
Juggling too many things today. I just fetched the changes from your repo, and did a local diff. Looks fine to me, breaks precedent about containing tags to their own spot, but has some great examples, makes sense in context, and includes a picture, though I'm not sure why the text is repeated twice in your picture.

**Pull request merged**
