### PR TITLE
Revert "PcgenFtlTestCase: stop deleting output file (#5842)"

### PR DESCRIPTION
**Pull request by Zaister**
This reverts commit 1025ae8c. The commit added syntactially incomplete and broke the build.

Signed-off-by: Stefan Radermacher <stefan@zaister.de>

### CODE REVIEW

**Comment by grimreaper** [comment]
How is this broken? I'm not sure I understand

**Comment by Zaister** [comment]
Check out the code from that commt, there seems to be something missing, the code is incomplete, not even that braces are balanced - the try block just ends abruptly at the brace closing the class.

**Comment by LegacyKing** [comment]
@Zaister One of the character unit tests is failing - nodes dropped from 115 to 113

**Comment by LegacyKing** [comment]
I think we can close as we have a fix?

**Comment by starcraftman** [comment]
I assume so, no longer relevant.

**Pull request closed without merging**
