### PR TITLE
DATA-3103

### PR DESCRIPTION
**Pull request by mjmeans**

### CODE REVIEW

**Comment by mjmeans** [comment]
Rebasing seems to have made it worse. I even tried 'git rebase -f PCGen/master'. I have no idea how to fix this.

**Comment by LegacyKing** [comment]
Good lord Mark, this is a mess. Make a branch called 'fix-pfsa' from this existing branch. REBASE from Master. Stop merging branches together, you don't need to include MASTER fixes into a fix branch, a fix branch should JUST be the changes you are making. Just cherry pick what you need if it's crucial to your fix branch, but this is rarely needed unless you're doing some hard core code work. 

In fact, scratch all what I just said. Switch to Master at a CLEAN state. Create a New Branch called "fixes-pfs-a", cherry pick the THREE commits from your previous fix branch, then push that up.

**Comment by mjmeans** [comment]
This apparently is what is automatically happening with the official GitHub for Windows client. I don't know how to cherry pick individual PR's from another branch. There is no mechanism in the official GitHub for Windows GUI client that I know of that will do what you ask.

**Comment by mjmeans** [comment]
The merges into master come from the official GitHub for Windows client. When viewing my master branch it periodically tells me that PCGen/pcgen has changes and asks if I want to get them. I click yes. It then shows the 'Merge remote-tracking branch 'refs/remotes/PCGen/master' entry in master. If I create a new branch, these branches also have this entry.

**Comment by mjmeans** [comment]
The remote PCGen points to 'https://github.com/PCGen/pcgen.git'.
I just tried the following:
1. git checkout master
2. git rebase -f PCGen/master
3. git checkout Fix-PFS
4. git rebase -f master
Then I closed the command line and clicked the Sync button in the GitHub for Windows client.

**Pull request closed without merging**
