### PR TITLE
CODE-2929 CONVERTER 6.06: PREALIGN silently stripped in conversion!

### PR DESCRIPTION
**Pull request by LegacyKing**

### CODE REVIEW

**Comment by jdempsey-au** [comment]
Cool, that's certainly part of the issue, but we'll need further work to
stop the PREALIGNs being written back out without the alignments.

Cheers,
James Dempsey

**Comment by LegacyKing** [comment]
Apparently our build cannot find the maven jep library... odd, mine passed.

**Comment by LegacyKing** [comment]
Should I remove the non-parse code you mentioned? Or is there a better method?

**Comment by LegacyKing** [comment]
So this:

if (Globals.getContext().getReferenceContext().getConstructedObjectCount(PCAlignment.class) == 0)
{
	// There are no alignments for this game mode, so we
	// do not do prereqs.
	prereq.setKey("");
	prereq.setOperator(PrerequisiteOperator.EQ);
}

just comment out or remove then?

**Comment by jdempsey-au** [comment]
No, I wouldn't mess with that. Its a question for @thpr now I think

Cheers,
James

**Comment by LegacyKing** [comment]
Good, cause I'm trying to make heads and tails of the file, and I'm confused. Are we still supporting the number version of PREALIGN? (Is that where the formula is factoring?)

I'll re-assign the tracker to @thpr then.

Cheers,

**Comment by jdempsey-au** [comment]
This code fix is an improvement to current, so I'll merge it.

**Pull request merged**
