### PR TITLE
Remove unneeded temporary file

### PR DESCRIPTION
**Pull request by Ampersandrew**
Thought I was going to use this as an interim fix for SABs.  I've found I don't need it as I'm working.

### CODE REVIEW

**Comment by LegacyKing** [comment]
I have a failing test. Please recheck.

**Comment by LegacyKing** [comment]
pcgen.persistence.lst.DataTest > missingFilesTest FAILED

    org.junit.ComparisonFailure: Some data files are missing. expected:<[]> but was:<[Missing file modern/wizards_of_the_coast/msrd/arcana/basics/arcanabasics_abilities_class_sab.lst used by modern/wizards_of_the_coast/msrd/arcana/basics/arcanabasics.pcc<br>

    Missing file modern/wizards_of_the_coast/msrd/arcana/basics/arcanabasics_abilities_class_sab.lst used by modern/wizards_of_the_coast/msrd/arcana/msrd_arcana.pcc<br>

    Missing file modern/wizards_of_the_coast/msrd/arcana/basics/arcanabasics_abilities_class_sab.lst used by modern/wizards_of_the_coast/msrd/arcana/msrd_arcana.pcc<br>

**Comment by Ampersandrew** [comment]
Andrew, did you see this?  I think that's the problem fixed.

I found it myself before you posted, but I was taking the time to figure out git's interactive add to only commit parts of the changes to a file.

**Comment by LegacyKing** [comment]
No, unless you post, I do not get notified of new commits in the PR.

**Comment by Ampersandrew** [comment]
Ah right.  I'll bear that in mind.

Thanks

**Pull request merged**
