### PR TITLE
CODE-2865 Fix: [6.05.04-dev] PREFACT fails to parse correctly

### PR DESCRIPTION
**Pull request by thpr**

### CODE REVIEW

**Comment by LegacyKing** [comment]
Passes tests, and wow, that would have been a tough fix for me to attempt. New files "reducible" and "OutputDB". Nice.

**Comment by LegacyKing** [comment]
Are we waiting for @jdempsey-au to review this @thpr ?  If so, let me know. I have a bunch of FACT work I'm waiting to commit for this fix.

**Comment by jdempsey-au** [comment]
@LegacyKing Yes I thought this would be a bit more than a simple fix.

**Comment by jdempsey-au** [comment]
@thpr I'm seeing a couple of test failures in the slowtest set:

pcgen.core.prereq.PreFactSetTest > testFact FAILED
    junit.framework.AssertionFailedError: Character's deity should match pantheon
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.TestCase.assertTrue(TestCase.java:192)
        at pcgen.core.prereq.PreFactSetTest.testFact(PreFactSetTest.java:72)

pcgen.core.prereq.PreFactTest > testFact FAILED
    junit.framework.AssertionFailedError: Character should be a matching race
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.TestCase.assertTrue(TestCase.java:192)
        at pcgen.core.prereq.PreFactTest.testFact(PreFactTest.java:72)

I think the source is pcgen.output.publish.OutputDB.getIterable(OutputDB.java:178)
`String k2 = (keys.length == 1) ? keys[1] : "";`
which should be 
`String k2 = (keys.length > 1) ? keys[1] : "";`

**Comment by thpr** [comment]
doh, yes see new PR

**Pull request merged**
