### PR TITLE
[6.08] Fix bug: DATA-3774 - Accomplished Sneak Attacker Feat from Dir…

### PR DESCRIPTION
**Pull request by LegacyKing**
…ty Tactics Toolbox is not increasing number of Sneak Attack Dice

### CODE REVIEW

**Comment by milot-mirdita** [comment]
Hi, I reported the issue on Jira. I don't think that this is quite correct yet.
This part needs to be implemented or you can have a [Rogue with 2d6 sneak attack damage at level 1](https://github.com/PCGen/pcgen/files/2635844/ACA.Bug2.pcg.zip):

  Your number of sneak attack dice cannot exceed %1.|ceil(TL/2)

**Comment by LegacyKing** [comment]
There you go - https://github.com/PCGen/pcgen/pull/4523

**Comment by milot-mirdita** [comment]
I am not sure thats a good fix. There are things that can add sneak attack dice [1][2]. Only ASA is specifically limited. Additionally a Ninja (or Vivisectionist or whatever else) can also take the ASA feat and have the wrong number of sneak attack dice shown:

[[1] Deific Obedience](http://aonprd.com/DeityDisplay.aspx?ItemName=Shax)
[[2] Someone who really overdid it with sneak attack dice](https://rpg.stackexchange.com/questions/109024/what-is-the-maximum-amount-of-sneak-attack-dice-you-can-roll-with-1-full-attack)

Sorry for all the trouble :)

**Comment by LegacyKing** [comment]
I officially detest this feat. Any feat you can take that is useful in limited situations, and then neutered in others is a PAIN! (Dodge from 3.x edition is a perfect example).

**Pull request merged**
