### PR TITLE
Re-write FAQ: Submitting a bug report.

### PR DESCRIPTION
**Pull request by LiaungYip**
Note, this page has been re-written in Markdown.
The HTML is produced by `pandoc .\faqsubmittingabugreport.md -o .\faqsubmittingabugreport.html --toc --css=../pcgen.css`.

Also includes some additions to the CSS, to support `pandoc` table of contents and figures.

### CODE REVIEW

**Comment by LiaungYip** [comment]
Whoops, I also edited `faqsubmittingabugreport.html` in #373 so there will be a merge conflict. The version of `faqsub...html` in this PR should completely replace the version in #373.

**Comment by LegacyKing** [comment]
I believe the correct etiquette is to fix the PR so it will merge... Can you handle that please?

**Comment by LiaungYip** [comment]
Okay, I think I've un-screwed it. I'm still new to the whole business of "playing nice with others", also known as "merging". Sorry for the messy commit history.

**Comment by LegacyKing** [comment]
Impressive pictures.

**Comment by LegacyKing** [comment]
Just something else I realized... we have nothing testing the docs, so the merge ability and review is the only key here. The tests are only for code and data changes. Keep up the good work!

**Comment by LiaungYip** [comment]
The pictures are done using the screenshotting tool [Greenshot](http://getgreenshot.org/), which I recommend highly.

As far as doc testing goes - should investigate if it's possible to automatically run `tidy` and `linkchecker` as part of the continuous integration builds, to flag up errors like broken HTML (i.e. an `<a>` tag is opened, but never closed, `</a>`) and broken links (there are a lot of broken links.)

**Pull request merged**
