### PR TITLE
Bug Fix - CODE-2993: Thumbnail exports poorly to pdf

### PR DESCRIPTION
**Pull request by cpmeister**

### CODE REVIEW

**Comment by LegacyKing** [comment]
Does the input matter if it's a jpg or png or anything else? I see we now export to png. Just curious.

**Comment by cpmeister** [comment]
It doesn't really matter. But JPEG has limitations when it comes to transparency, an issue that png doesn't have. The images may look slightly different (due to them using different types of compression) but the difference should not be very noticeable or even matter that much to the end user.

**Comment by cpmeister** [comment]
As far as the input types, we still support jpeg during thumbnail selection we just change it to png during export.

**Comment by LegacyKing** [comment]
Sounds good. The change is trivial. I'll give it a good test. Thanks!

**Pull request merged**
