### PR TITLE
Installer fixes

### PR DESCRIPTION
**Pull request by javydreamercsw**

### CODE REVIEW

**Comment by javydreamercsw** [comment]
Really hope this was tested and fixed the issue without any side effects.

**Comment by karianna** [comment]
@javydreamercsw I'd assumed you'd tested this locally :-).  Was there some sanity testing done or should we roll this back?

**Comment by javydreamercsw** [comment]
Yes I did. I meant that it didn't break any other task, etc.

I built and tested the installer, nothing else. I hope the tests would have failed if something else broke.

**Comment by karianna** [comment]
Should be good :-)

**Pull request merged**
