### PR TITLE
Revert "Replace SwingWorker Version 3 with JDK 6+ SwingWorker (#4335)"

### PR DESCRIPTION
**Pull request by grimreaper**
This reverts commit 18e1e790b44ccbe225fa030c6bf89860868f80f9.

### CODE REVIEW

**Comment by LegacyKing** [comment]
Status Bar and Source Load never truly complete on Windows OS. Confirmed by @javydreamercsw

**Comment by grimreaper** [comment]
omg. If this is windows specific I'll so annoyed. It was so painful to test last time.

**Comment by karianna** [comment]
It happened on Mac Os X as well.

**Comment by javydreamercsw** [comment]
Yes. My confirmation was on Mac. Sorry.

**Pull request merged**
