### PR TITLE
Use modern TravisCI Infrastructure

### PR DESCRIPTION
**Pull request by grimreaper**
This moves us to using the TravisCI container based infrastructure.

### CODE REVIEW

**Comment by LegacyKing** [comment]
And we're now conflicting... please address @grimreaper

**Comment by grimreaper** [comment]
The packages shouldn't be changing anything - it just changes the way they get installed.

**Comment by LegacyKing** [comment]
@grimreaper fix

**Comment by grimreaper** [comment]
this needs to be reworked a bit now. Closing until I have time to handle it.

**Pull request closed without merging**
