### PR TITLE
Requesting a pull to PCGen:master from grimreaper:bump2  Bump sprint to 3.2.14  To be applied after PR #643

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by LegacyKing** [comment]
@grimreaper you can set up travis to work on your local repo before you send the PR. That has helped me often in the past with big changes.

**Comment by jdempsey-au** [comment]
Closing this duplicate.

**Comment by grimreaper** [comment]
That seems amazing.  How does one do that?  Can you point me to the docs?  Is it just sign up for travis and follow some wizard or is it more complicated?

**Comment by LegacyKing** [comment]
Go into your github fork. Settings > Webhooks & services.

Select Travis.

Follow the instructions here:

Travis CI is a distributed continuous integration service.

By enabling this hook, Travis CI will listen to push and pull request
events to trigger new builds.

For more details about Travis, go to http://docs.travis-ci.com
<http://docs.travis-ci.com/>.


    Automatic configuration from Travis CI

We recommend using the Travis profile page
at https://travis-ci.org/profile to manage your hooks.
For private repositories, use https://magnum.travis-ci.com/profile.


    Travis CI Status

Travis CI status page: http://status.travis-ci.com
<http://status.travis-ci.com/>


Cheers,

**Pull request closed without merging**
