### PR TITLE
remove @author, updated on, created on, and other useless remarks

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by thpr** [comment]
conflicts

**Comment by grimreaper** [comment]
resolved

**Comment by LegacyKing** [comment]
@grimreaper 
Not touching this, sorry. You have an entire java file hidden inside...

**Comment by grimreaper** [comment]
looks like a merged conflict on a deleted files; closing and will fix separately

**Comment by grimreaper** [comment]
and resolved

**Comment by grimreaper** [comment]
#2361

**Pull request closed without merging**
