### PR TITLE
Add visible for testing annotation and enable use of findbugs

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by thpr** [comment]
No, no guava due to size

**Comment by grimreaper** [comment]
Why close this?

**Comment by grimreaper** [comment]
It isn't a distribution dependency. Are you concerned about the compilation dep size as well?

**Comment by grimreaper** [comment]
also, have we considered running proguard on the jar post-build? It might drastically reduce the size.

**Pull request closed without merging**
