### PR TITLE
Data 3533 make wildblooded bloodlines selectable

### PR DESCRIPTION
**Pull request by allardhoeve**
This is not the correct fix for bloodlines, but the system is more complex than I know how to fix. One of the problems is that since 796429d83ad6c588cf8a0ec310a28be75a6da56d all bloodlines need fixing. If there is documentation on how to do this, I'd be happy to help.

This works for all bloodlines, except Linnorm (needs some solution to pop up a second chooser) and Primal (needs some solution to choose one of four elements). These will (looking at the Draconic) bloodline, probably be more Ability Pools?

### CODE REVIEW

**Comment by allardhoeve** [comment]
The awkward master merge is because there is a file called `gradlew.bat` with weird line endings in the way of merging. I cannot get a clean checkout anymore :(

**Comment by LegacyKing** [comment]
pcgen.persistence.lst.DataLoadTest > testLoadSources[Pathfinder RPG Core Supplements] FAILED
    org.junit.ComparisonFailure: Errors encountered while loading Pathfinder RPG Core Supplements expected:<[]> but was:<[Invalid use of MULT:YES Ability Linnorm (Wildblooded Draconic) Bloodline where a target [parens] is required,
    PLEASE TAKE NOTE: If usage locations are reported, not all usages are necessary illegal (at least one is),
    Invalid use of MULT:YES Ability Primal (Wildblooded Elemental) Bloodline where a target [parens] is required,
    PLEASE TAKE NOTE: If usage locations are reported, not all usages are necessary illegal (at least one is)]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at pcgen.persistence.lst.DataLoadTest.testLoadSources(DataLoadTest.java:160)

**Comment by allardhoeve** [comment]
Hehe no, I was afraid of that. Is that new way documented somewhere? @Llisandur

**Comment by Llisandur** [comment]
Not yet. I'm working out the documentation/templates at the moment.

**Comment by allardhoeve** [comment]
Let's leave this quick fix open in case someone else runs into the problem, then delete the PR when the issue is resolved?

**Comment by Llisandur** [comment]
Here's what I have so far for a template. I still need to see how other bloodline-affecting archetypes work so I can add them in.


[Sorcerer Bloodline Template.txt](https://github.com/PCGen/pcgen/files/1702885/Sorcerer.Bloodline.Template.txt)

**Comment by allardhoeve** [comment]
Wow, that is an impressive template. Is this all needed for every bloodline?

If you don't mind my asking, what is the rationale for the overhead?





Op wo 7 feb. 2018 12:50 schreef Regan Anderson <notifications@github.com>:

**Comment by Llisandur** [comment]
Basically, to support all of the features of the bloodline and all the ways to gain a bloodline/bloodline power. The overhead is basically a how-to on using the template; you can also just do replaces on the overhead and it'll fill out the template with all of the basics. Things in the TYPE tag of the power abilities are the only things that you have to scroll down and edit individually. Of course, you'll have to scroll down to the powers anyway to add in the individual variables and bonuses and things.

**Pull request closed without merging**
