### PR TITLE
Normalize line endings

### PR DESCRIPTION
**Pull request by tildar**
Just normalizing gradlew.bat line endings.
My git status always showed it as modified.
git diff gradlew.bat showed all lines as modified.
git diff -w gradlew.bat was silent.

### CODE REVIEW

**Comment by LegacyKing** [comment]
I don't see anything. @karianna ?

**Comment by tildar** [comment]
It's just odd on my end. Even a fresh clone in a clean dir shows gradlew.bat as modified.

I simply did a git add gradlew.bat on the file that the fresh clone spits out at me, commit/push...

It's possible that I have an issue in git on my side to track down?

**Comment by tildar** [comment]
More digging and I believe  this has something to do with the changes done to .gitattributes about 4 months ago.

**Comment by karianna** [comment]
I assume this .bat file works fine for you on windows?  In that case I'm happy to accept.

**Comment by tildar** [comment]
@karianna I do not have a windows box available to me for testing, strictly Linux on my end.
Perhaps someone else can verify?

**Comment by LegacyKing** [comment]
@karianna I use the bat file for testing. It looks safe to merge.

**Comment by tildar** [comment]
I've just had the chance to verify that new clone no longer gives me a modified gradle.bat and that it is still crlf as needed. So, either this and/or #4145 has fixed the issues for me.  Thanks

**Pull request merged**
