### PR TITLE
Fix #3453: Pathfinder: choose 'Aasimars' race got exception

### LINKED ISSUE #3453: Pathfinder: choose 'Aasimars' race got exception
Steps:
1. Select source: 'Pathfinder RPG Core Supplements'
2. File -> new
3. Select race: 'Aasimars' (actually many other non core races also has same issue)

Problem: 
1. Race tab: race name is empty (it should show 'Aasimars')
2. Feats & Abilities -> Race Traits tab is missing

Related error message shown below
```
java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(Unknown Source)
	at pcgen.core.BioSet.generateHeightWeight(BioSet.java:578)
	at pcgen.core.BioSet.randomize(BioSet.java:210)
	at pcgen.cdom.facet.BioSetTrackingFacet.dataAdded(BioSetTrackingFacet.java:66)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:264)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:205)
	at pcgen.cdom.facet.base.AbstractItemFacet.set(AbstractItemFacet.java:77)
	at pcgen.cdom.facet.input.RaceInputFacet.directSet(RaceInputFacet.java:116)
	at pcgen.cdom.facet.input.RaceInputFacet.set(RaceInputFacet.java:58)
	at pcgen.core.PlayerCharacter.setRace(PlayerCharacter.java:3497)
	at pcgen.gui2.facade.CharacterFacadeImpl.setRace(CharacterFacadeImpl.java:1894)
	at pcgen.gui2.tabs.SummaryInfoTab$ComboBoxModelHandler$6.commitSelectedItem(SummaryInfoTab.java:954)
	at pcgen.gui2.tabs.models.DeferredCharacterComboBoxModel$1.run(DeferredCharacterComboBoxModel.java:132)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

I have prepared a fix in local, please indicate if I could go ahead to prepare a pull request?

### PR DESCRIPTION
**Pull request by simiczhang**
Fix by removing unneccessary & unchecked call to genderTok.nextToken()

### CODE REVIEW

**Comment by LegacyKing** [comment]
Just an FYI, I fixed the data files that were the cause of this, but I do believe this should be included.

**Comment by LegacyKing** [comment]
Deadline for review/merge next week. I'll merge if no further feedback from the code team.

**Comment by milesoc** [comment]
Oh! I'm not a pcgen contributor, was trying to fix this same issue as I'd run into it. Fixed it a slightly different way:
https://github.com/PCGen/pcgen/pull/3507

Let me know if you think it's still worthwhile to short-circuit when height and weight are not available, otherwise I'll close out my PR. Thank you for working on this :)

**Comment by LegacyKing** [comment]
Biosettings are an old system, and very fragile. I'd rather fix than ignore.

**Pull request merged**
