### PR TITLE
gradle: update to 4.8

### PR DESCRIPTION
**Pull request by grimreaper**
This is required to run Gradle under JDK 10

Custom 'wrapper' task is deprecated and thus removed.

### CODE REVIEW

**Comment by karianna** [comment]
See #4102 for discussion as well

**Comment by grimreaper** [comment]
Ugh. I thought we fixed those issues some time ago. Feel free to regen and push the branch.

**Comment by tildar** [comment]
@grimreaper Yes, the issues was "fixed" in .gitattributes some time ago. This and/or 4102 are needed to finish what was started with #3804.

**Comment by karianna** [comment]
OK #4102 was merged

**Comment by karianna** [comment]
Hmm, yet the white space issue remains.

**Comment by karianna** [comment]
I'm just going to merge this and a subsequent PR can go in to fix line endings if required.

**Pull request merged**
