### PR TITLE
Implement ADMIN-52

### PR DESCRIPTION
**Pull request by javydreamercsw**
After building the project, you'll have all the jars and exe in root/pcgen folder for you to run there.

Distributions seems fine to me just need an expert eye to take a look.

### CODE REVIEW

**Comment by LegacyKing** [comment]
Major failing. Looks like the imports need to be fixed to reflect directory structure changes.

**Comment by javydreamercsw** [comment]
I'm unable to reproduce. All those imports are correct and compile on my local copy. The PR process might be not doing it right. Hard to tell without access to the checked out repository. That I like about Jenkins.

**Comment by javydreamercsw** [comment]
There's no change needed to the imports, all is handled in the gradle files pointing to new source root.

**Comment by javydreamercsw** [comment]
Bump...

**Comment by LegacyKing** [comment]
This is giving an unknown repo and conflicts galore. :(   Without the input of the other major players, I'm not comfortable making a broad change in absence of the team input.

**Comment by LegacyKing** [comment]
I think it might be safer and easier to just EXPORT into another folder completely, instead of changing the existing structure. I would feel fine approving that without the team input since that is simply the BUILD.

**Comment by javydreamercsw** [comment]
Please update the issue with your proposed changes so I can take a look.

**Comment by javydreamercsw** [comment]
I closed since this approach is no longer desired.

**Pull request closed without merging**
