### PR TITLE
Archetype fact replacement

### PR DESCRIPTION
**Pull request by LegacyKing**
@jdempsey-au I appear to have a couple of Code patches in this??? Can you verify these are safe to merge...

### CODE REVIEW

**Comment by jdempsey-au** [comment]
@LegacyKing The code changes are safe - they are just setting back the EOLs for those files - this is caused by the old source branch for Tom's recent commit. We'll have to watch those files to see if they continue to cause problems.

**Comment by LegacyKing** [comment]
I also have three deprecated files that are persisting between branches...

**Comment by LegacyKing** [comment]
FYI - Sourceforge dependencies are failing... that's why Travis is failed.

**Comment by LegacyKing** [comment]
> Could not resolve all dependencies for configuration ':runtime'.

   > Could not resolve cobra:cobra:0.98.4-pcgen.

     Required by:

         build:pcgen:6.05.04-SNAPSHOT

      > Could not GET 'http://pcgen.sourceforge.net/mvnrepo/cobra/jars/ivy-0.98.4-pcgen.xml'.

         > Connection reset

   > Could not resolve mrj:MRJ141Stubs:0.

     Required by:

         build:pcgen:6.05.04-SNAPSHOT

      > Could not GET 'http://pcgen.sourceforge.net/mvnrepo/mrj/jars/ivy-0.xml'.

         > Connection reset

   > Could not resolve jep:jep:2.4.1.

     Required by:

         build:pcgen:6.05.04-SNAPSHOT

      > Could not GET 'http://pcgen.sourceforge.net/mvnrepo/jep/jars/ivy-2.4.1.xml'.

         > Connection reset

---
I've run eclipse, and tests are passing.

**Pull request merged**
