### PR TITLE
Code-3263

### PR DESCRIPTION
**Pull request by javydreamercsw**
Add requested changes. Sadly I can't test this changes so hopefully some one else can.

### CODE REVIEW

**Comment by tildar** [comment]
@javydreamercsw Travis failded due to wget failing to dl zlib128-dll.zip
This has nothing to do with any changes in your PR. It's a problem on the travis side of things, and seemed to be happening  a lot lately. I'm looking at a possible fix, and should have it up here soon.

**Comment by javydreamercsw** [comment]
That's what I saw in the logs and hoped it had nothing to do with my changes. Was not aware of it being failing a lot. Thanks!

**Comment by LegacyKing** [comment]
Fixed conflict, rerunning Travis.

**Comment by javydreamercsw** [comment]
Still some test failures.

**Comment by tildar** [comment]
@LegacyKing this should pass travis now that you have fixed the issue that was causing (No such file or directory) errors.

**Comment by LegacyKing** [comment]
Nope: 

```
warning: File /a is disabled for non Win32 platforms. (/home/travis/build/PCGen/pcgen/installers/win-installer/pcgen.nsi:172)
File: "/home/travis/build/PCGen/pcgen/build\nsis\..\..\jre\jre_64\jre\*.*" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "/home/travis/build/PCGen/pcgen/installers/win-installer/pcgen.nsi" on line 172 -- aborting creation process
:buildNsis FAILED
```

**Comment by javydreamercsw** [comment]
Hmmm... This is weird. The download occurred for sure or it would have failed. Only thing I can think off would be if there was an empty folder there, it won't attempt the download but that shouldn't be the case on Travis.

**Comment by javydreamercsw** [comment]
Id did download looking at the logs:

> :downloadJRE
Downloading JRE 10.0.1 from https://cdn.azul.com/zulu/bin/zulu10.2+3-jdk10.0.1-win_x64.zip
Download https://cdn.azul.com/zulu/bin/zulu10.2+3-jdk10.0.1-win_x64.zip
Unzip jre_64.zip
Downloading JRE 10.0.1 from https://cdn.azul.com/zulu/bin/zulu10.2+3-jdk10.0.1-win_i686.zip
Download https://cdn.azul.com/zulu/bin/zulu10.2+3-jdk10.0.1-win_i686.zip
Unzip jre_32.zip

I'll start a build on my virtual machine and see how it goes.

**Comment by javydreamercsw** [comment]
Was unable to get a machine to do this.

**Comment by mertonmonk** [comment]
So what needs to be changed to make this successfully build in Travis?

**Comment by javydreamercsw** [comment]
I would have to look at it deeper. Seems to be complaining about the JRE files not being there.

**Comment by karianna** [comment]
I've restarted the travis build to see if this clears.

**Comment by karianna** [comment]
@javydreamercsw still fails on travis - did you have any luck running this locally?

**Comment by javydreamercsw** [comment]
Haven't had a time to check yet. Will try after lunch.

**Comment by javydreamercsw** [comment]
I fixed the issue locally but have no means to check the resulting installer right now. Hopefully someone else can take a look.

**Comment by javydreamercsw** [comment]
Did you check the end result, i.e. the installer?

**Comment by karianna** [comment]
Worked OK on my Windows inside a virtual box, but other folks will have to test it in more depth during the next release

**Pull request merged**
