### PR TITLE
npcgen: remove it

### PR DESCRIPTION
**Pull request by grimreaper**
- this code is never used or called.
- it uses JEP which will need to be modified eventually

### CODE REVIEW

**Comment by thpr** [comment]
This needs discussion

**Comment by karianna** [comment]
> * this code is never used or called.
> * it uses JEP which will need to be modified eventually

You sure it's not being used?

**Comment by grimreaper** [comment]
> > * this code is never used or called.
> > * it uses JEP which will need to be modified eventually
> 
> You sure it's not being used?

It has no UI, and removing the code has no impact. How else can it be used?

@thpr re discussion: sure. I could start a thread on the ML

**Comment by grimreaper** [comment]
sent a mail to the mailing list

**Comment by LegacyKing** [comment]
Approved - As far as my opinion counts

**Comment by grimreaper** [comment]
https://pcgen.groups.io/g/pcgendevelopers/topic/removal_of_npcgen/31513007?p=,,,100,0,0,0::recentpostdate%2Fsticky,,,100,2,0,31513007

I'll send an email to users as well

**Pull request merged**
