### PR TITLE
[build] bump java from 14 to 16

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by LegacyKing** [comment]
Yes, the URL is dead. https://gluonhq.com/download/javafx-16-0-1-jmods-windows/ gives a wayback message.

**Comment by karianna** [comment]
Address need to be https://gluonhq.com/download/javafx-16-jmods-windows/

**Comment by karianna** [comment]
Travis needs to be at 16, trying that now...

**Comment by karianna** [comment]
run tests

**Comment by karianna** [comment]
Updated GitHub action as well

**Comment by karianna** [comment]
OK, so we actually needed to bump Gradle to 7.1.1 and do a bunch of other stuff. I'll see if I can push into this PR else make my own.

**Comment by karianna** [comment]
Closing this in favour of #6528

**Pull request closed without merging**
