### PR TITLE
Move libs back to root

### PR DESCRIPTION
**Pull request by javydreamercsw**
As requested by @LegacyKing.

### CODE REVIEW

**Comment by karianna** [comment]
I think this needs rebasing or something?  Seems to reapply some of Tom's previous work.

**Comment by javydreamercsw** [comment]
I did rebase when I updated from upstream.

**Comment by LegacyKing** [comment]
Doesn't look like it. If you rebased, then the only commits should be exclusively those on the branch, nothing else. The easiest fix for this, update master, branch from master, cherry pick your commits back in, then push.

**Comment by javydreamercsw** [comment]
Will recreate.

**Pull request closed without merging**
