### PR TITLE
remove last JavaFX dependency

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by karianna** [comment]
closes #3761

**Comment by karianna** [comment]
If acceptable just use the squash and merge option.

**Comment by LegacyKing** [comment]
@karianna we must teach you the ways of REBASE... But LGTM.

**Comment by LegacyKing** [comment]
@PCGen/code-team-reviewers  Just to save time, please Merge if you feel the PR is good to be included. In some cases, I am waiting on these before I set to release as there is an actual impact on my ability to use the program. Thanks!

**Pull request merged**
