### PR TITLE
Fix GUI on OS X with Java >= 9

### LINKED ISSUE #4038: Hang at Initialize UI
Heya folks. Having some issues running the application on mac. It is currently hanging after open .jar file. Have tried multiple versions, 6.06.1 & 6.07.7 & 6.07.8. Have also reinstalled java JRE and JDK multiple times and restarted.

My java log is as follows.

`21:33:17.733 INFO main Main:140 Starting PCGen v6.07.08
21:33:17.875 INFO main LanguageBundle:134 Initialising language bundle with locale en_US.
21:33:34.341 SEVERE main Main:544 Uncaught error - ignoring
java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler
	at pcgen.gui2.PCGenUIManager.initializeGUI(PCGenUIManager.java:52)
	at pcgen.system.Main.startupWithGUI(Main.java:258)
	at pcgen.system.Main.main(Main.java:161)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more
`

### PR DESCRIPTION
**Pull request by romen**
Tested with Java 10, but the relevant changes happened in Java 9.

Fixes #4038

### CODE REVIEW

**Comment by romen** [comment]
@karianna

No, sorry I planned to highlight this in the pr description, but forgot to do so.

Do you have suggestions on how to make it support both? I see a problem at build time to generate an universal release and at runtime to select either this or the old implementation depending on the JRE version.

**Comment by karianna** [comment]
You can use multi-release Jars to pull this off. https://blog.codefx.org/tools/multi-release-jars-multiple-java-versions/

**Comment by romen** [comment]
Thanks for the link.
I was reading into https://blog.gradle.org/mrjars#how-to-create-a-multi-release-jar-with-gradle and the reasons why gradle developers discourage from using MRJARs.

Unfortunately looking at the current gradle profile and the information in that post, not having any experience with gradle, it looks like these changes are above my skill level.

**Comment by romen** [comment]
Probably it's just better to write somewhere what is the maximum supported version of JRE and let the user decide if they want to install and use Java 8.

Java 8 is the current LTS, and the next LTS (Java 11) is scheduled for September 2018.
Anyway support for Java 8 is scheduled until January 2019 (for commercial purposes) and December 2020 for other uses. 

Probably by then you will have already integrated support for Java 11 or overhauled the whole project!

**Pull request closed without merging**
