### PR TITLE
Pcgio handler

### PR DESCRIPTION
**Pull request by LegacyKing**
Update to requested items.

### CODE REVIEW

**Comment by LegacyKing** [comment]
@jdempsey-au or @thpr please review

**Comment by LegacyKing** [comment]
@jdempsey-au we able to get this in?

**Comment by LegacyKing** [comment]
@jdempsey-au we have two updated PRs, will we be adding these or are we waiting for the new development cycle? Looking to begin the release process in six hours.

**Comment by jdempsey-au** [comment]
As these are not bug fixes they should go into the next dev cycle. I'm looking forward to having them merged though! It is always good to make good use of the work people have put in.

**Pull request merged**
