### PR TITLE
CODE-3021: Upgrade code base to use Java 8

### PR DESCRIPTION
**Pull request by cpmeister**

### CODE REVIEW

**Comment by LegacyKing** [comment]
You going to change the valid compile version to 1.8?

**Comment by LegacyKing** [comment]
image

alter the travis.yml to the oraclejdk8, that should fix the failed test.

**Comment by grimreaper** [comment]
any reason not to merge this? It would allow for even more code simplification later.

**Comment by LegacyKing** [comment]
Hi @grimreaper not sure if you see the same things the gatekeepers do... but 
1. The branch is in conflict and cannot be merged
2. Travis reports at least one failed test, which means this would halt all autobuilds

Cheers,

**Comment by LegacyKing** [comment]
@cpmeister how goes the effort here???

**Pull request merged**
