### PR TITLE
Normalize all the line endings for text files.

### PR DESCRIPTION
**Pull request by jdempsey-au**
This massive change sorts out the line endings for text files in pcgen. In all this only two files have content changes: .gitattributes (tweaking the text settings) and code/src/java/pcgen/resources/lang/LanguageBundle.properties  (removing a key to test the fix)

A comparison using git diff -w between pcgen/pcgen and jdempsey-au/pcgen will confirm this change set

### CODE REVIEW

**Comment by jdempsey-au** [comment]
@skylarhiebert  @allardhoeve @thpr @LegacyKing - it would be great if you could have a look please by way of a review. I'm aiming to do a merge tomorrow night (approx 30 hours)

**Comment by LegacyKing** [comment]
None of the Content Files seem to be in this PR. Not exactly sure what you expect my review to hit. The concept we discussed earlier seems to resonate well, and the blog article made sense to me. Definitely approve of the concept, and we can blow up a clone with option 2 to see if that is a viable deal.

I'm noticing you don't use branches... I'm going to have to fetch your changes to have any in-depth review though. The Diff on here isn't much for EoL review.

**Comment by allardhoeve** [comment]
So a hidden feature is that you can have Github ignore white-space while
diffing.

https://github.com/PCGen/pcgen/pull/257/files?w=1

Changes seem okey to me but I think you smuggled a fubctional change in :-)

**Comment by LegacyKing** [comment]
What functional change are you talking about? Would that be the feat display, or the line endings selection?

**Comment by allardhoeve** [comment]
I mean the display. That is not really material to the PR subject. So maybe
it was a mistake?

**Comment by allardhoeve** [comment]
James, did you see this?

https://help.github.com/articles/dealing-with-line-endings/

**Comment by jdempsey-au** [comment]
@allard, yes that was one of my sources for this commit. Thanks for the tip on viewing without whitespace! The change was a local one which had triggered the issue in another branch. I was using it as a test to ensure the commit was correct but forgot to remove it before adding it in. The change will at worst cause a missing value report on the preferences UI, but the option concerned will be removed by a following PR.

@LegacyKing Yeah I normally use branches but used master for this as I was stuck there :( Thanks for testing the change out.

**Comment by allard** [comment]
That was @allardhoeve, not me!

**Comment by jdempsey-au** [comment]
Oops, sorry about that! Fixed now.

**Comment by allardhoeve** [comment]
@allard is my twin bro :wink: (not really)

**Comment by allardhoeve** [comment]
You could remove it and squash all the things...

**Comment by jdempsey-au** [comment]
@allardhoeve Good idea - I've removed that change.

**Pull request merged**
