### PR TITLE
BENEFIT: to DESC: in ACG

### PR DESCRIPTION
**Pull request by oiml**
Excluding Warpriest Bonus Feats.

### CODE REVIEW

**Comment by LegacyKing** [comment]
Why excluding Warprist bonus feats?

**Comment by oiml** [comment]
The warpriest bonus feats are counted as feats, so the BENEFIT part does show up on the outputsheet. I believe changing this to DESC: would remove the line break, which might not be wanted.

**Comment by LegacyKing** [comment]
If you look, the "Bonus Feats" in the file only attach the real feat to the PC. They are essentially placeholders. You can tell what an actual Feat is by CATEGORY:Feat. Those bonus feat benefits aren't being displayed in the UI.

**Comment by oiml** [comment]
Yeah, you're right. I also noticed that at least one class ability output looks weird now (bloodrager claws). I'll close this for now and reopen it when I'm done (probably tonight).

**Comment by oiml** [comment]
All BENEFIT: tags were converted and I hope that I got all of the double text entries.

**Pull request merged**
