### PR TITLE
CODE-2837

### PR DESCRIPTION
**Pull request by LegacyKing**
Non ascii in Javadoc causing build failure

### CODE REVIEW

**Comment by LegacyKing** [comment]
@jdempsey-au or @thpr for review.

**Comment by jdempsey-au** [comment]
I almost had a fix for this one ready to go - was too slow :)

**Comment by LegacyKing** [comment]
You weren't assigned to the JIRA, so I assumed it was open for grabs. ;)

**Comment by jdempsey-au** [comment]
Yep that's a fair assumption

**Pull request merged**
