### PR TITLE
Distribution enhancements

### PR DESCRIPTION
**Pull request by javydreamercsw**
1) Add _images and _universal to the core section of installer
2) Include 32 and 64 bit JRE in the full zip

### CODE REVIEW

**Comment by javydreamercsw** [comment]
@LegacyKing hopefully this is cleaner

**Comment by karianna** [comment]
`> Task :pfinttest
The command "travis_wait ./gradlew clean build installToRoot test compileSlowtest datatest pfinttest allReports buildDist buildNsis pcgenRelease" exited with 137.
`

**Comment by javydreamercsw** [comment]
I'm aware. I removed that. That command extends the timeout to 20 minutes but still failed since the pfinttest test is haninging.

**Comment by javydreamercsw** [comment]
That failure is not related. That test is hanging even on local tests.

**Pull request merged**
