### PR TITLE
Issue 4330

### PR DESCRIPTION
**Pull request by javydreamercsw**
1) Download OpenJDK from AdoptOpenJDK.
2) Include both 32 and 64 bit Java on installer.

### CODE REVIEW

**Comment by javydreamercsw** [comment]
This is not ready quite yet as 32 bit stuff is commented out since I was unable to find the distribution as mentioned on #4330.

**Comment by javydreamercsw** [comment]
Still waiting for the 32 bit distribution to finish this up.

**Comment by javydreamercsw** [comment]
The 32 bits is only on the nightly builds right now.

**Comment by javydreamercsw** [comment]
I suggest that when the 32 build is released we can swap both tho the released ones.

**Comment by javydreamercsw** [comment]
@karianna, @LegacyKing I Just committed the changes to have both 64 and 63 bits Java 11 in the installer. Right now it's using the nightly builds for both since 32 bits is not released yet.

**Comment by karianna** [comment]
```
warning: File /a is disabled for non Win32 platforms. (/home/travis/build/PCGen/pcgen/installers/win-installer/pcgen.nsi:172)
warning: File /a is disabled for non Win32 platforms. (/home/travis/build/PCGen/pcgen/installers/win-installer/pcgen.nsi:182)
Error: command Section not valid in Section
Error in script "/home/travis/build/PCGen/pcgen/installers/win-installer/pcgen.nsi" on line 186 -- aborting creation process
```

**Comment by javydreamercsw** [comment]
The warning is because is being build in a non-windows machine. Looking into the error.

**Pull request merged**
