### PR TITLE
Add Java 17 support

### PR DESCRIPTION
**Pull request by karianna**
Java FX and Java 17 make for interesting times.

### CODE REVIEW

**Comment by LegacyKing** [comment]
Can we put this into a development branch instead of master to master? Seeing a ton of merge commits.

**Comment by grimreaper** [comment]
this LGTM once conflicts are resolved.

**Comment by LegacyKing** [comment]
@karianna you able to resolve the conflicts?

**Comment by karianna** [comment]
Going to close this PR and try again

**Pull request closed without merging**
